// <auto-generated />
using System;
using DumbMcpMultiplexer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DumbMcpMultiplexer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("DumbMcpMultiplexer.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.McpServer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .HasColumnType("TEXT")
                        .HasColumnName("args");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<string>("ContainerImage")
                        .HasColumnType("TEXT")
                        .HasColumnName("container_image");

                    b.Property<string>("ContainerMounts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("container_mounts");

                    b.Property<string>("Containerfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("containerfile");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Env")
                        .HasColumnType("TEXT")
                        .HasColumnName("env");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("headers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PackageRunner")
                        .HasColumnType("TEXT")
                        .HasColumnName("package_runner");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("remote_http")
                        .HasColumnName("transport");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("CodeModeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("code_mode_enabled");

                    b.Property<bool>("CodeModeToonEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("code_mode_toon_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ProfileCapability", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.HasKey("ProfileId", "ServerId", "Kind", "Name");

                    b.ToTable("profile_capabilities", (string)null);
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ProfileServer", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.HasKey("ProfileId", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("profile_servers", (string)null);
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ServerCapability", b =>
                {
                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_json");

                    b.HasKey("ServerId", "Kind", "Name");

                    b.ToTable("server_capabilities", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ProfileCapability", b =>
                {
                    b.HasOne("DumbMcpMultiplexer.Models.ProfileServer", "ProfileServer")
                        .WithMany("Capabilities")
                        .HasForeignKey("ProfileId", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileServer");
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ProfileServer", b =>
                {
                    b.HasOne("DumbMcpMultiplexer.Models.Profile", "Profile")
                        .WithMany("ProfileServers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumbMcpMultiplexer.Models.McpServer", "Server")
                        .WithMany("ProfileServers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ServerCapability", b =>
                {
                    b.HasOne("DumbMcpMultiplexer.Models.McpServer", "Server")
                        .WithMany("Capabilities")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.McpServer", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("ProfileServers");
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.Profile", b =>
                {
                    b.Navigation("ProfileServers");
                });

            modelBuilder.Entity("DumbMcpMultiplexer.Models.ProfileServer", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
